/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import tbdex.sdk.tmp.Greeter
import tbdex.sdk.tmp.helloWorld
import java.io.File

private fun printSystemInfo() {
    // Print the operating system name and version
    try {
        val osRelease = File("/etc/os-release")
        if (osRelease.exists()) {
            osRelease.forEachLine { line ->
                println(line)
            }
        } else {
            println("/etc/os-release not found")
        }
    } catch (e: Exception) {
        println("Failed to read /etc/os-release: ${e.message}")
    }

    // Print the architecture
    try {
        val architecture = System.getProperty("os.arch")
        println("Architecture: $architecture")
    } catch (e: Exception) {
        println("Failed to get architecture: ${e.message}")
    }
}

fun main() {
    printSystemInfo()

    Greeter().greet()
//    helloWorld()
}
