#!/bin/bash

set -e

REPO_DIR=../../../../
IMAGE_NAME=tbdex_uniffi_x86_64-unknown-linux-musl_image
CONTAINER_NAME=tbdex_uniffi_x86_64-unknown-linux-musl_container

docker build -f $(pwd)/Dockerfile -t $IMAGE_NAME $REPO_DIR

docker run -d --name $CONTAINER_NAME $IMAGE_NAME

mkdir -p $REPO_DIR/bound/kt/src/main/resources;

docker cp $CONTAINER_NAME:/usr/src/myapp/target/release/libtbdex_uniffi.so \
  $REPO_DIR/bound/kt/src/main/resources/libtbdex_uniffi_x86_64_unknown_linux_musl.so

docker stop $CONTAINER_NAME
docker rm $CONTAINER_NAME