name: Kotlin CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  aarch64-apple-darwin:
    runs-on: macos-latest
    name: Load shared library on aarch64-apple-darwin target
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run tests
        run: |
          cd bound/kt
          mvn '-Dtest=SystemArchitectureTest#can load shared library' test

  x86_64-apple-darwin:
    runs-on: macos-12
    name: Load shared library on x86_64-apple-darwin target
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run tests
        run: |
          cd bound/kt
          mvn '-Dtest=SystemArchitectureTest#can load shared library' test

  x86_64-unknown-linux-gnu:
    runs-on: ubuntu-latest
    name: Load shared library on x86_64-unknown-linux-gnu target
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run tests
        run: |
          cd bound/kt
          mvn '-Dtest=SystemArchitectureTest#can load shared library' test

  x86_64-unknown-linux-musl:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    name: Load shared library on x86_64-unknown-linux-musl target
    steps:
      - uses: actions/checkout@v2
      - name: Install JDK 11 and Maven
        run: |
          apk update
          apk add openjdk11
          apk add maven
          apk add git
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run tests
        run: |
          cd bound/kt
          mvn '-Dtest=SystemArchitectureTest#can load shared library' test
